### PR TITLE
extracted form query methods

### PR DESCRIPTION
**Pull request by carlesjove**
I've just extracted some query methods to Form, where I think they should belong.

### CODE REVIEW

**Comment by plexus** [comment]
Nice! What do you think of renaming `method_is?` to just `method?`? Having both `is` and the question mark seem redundant.

**Comment by carlesjove** [comment]
It's fine by me. I just thought it was nicer to read with it `is`. Gimme a minute.

**Comment by carlesjove** [comment]
Done! :metal:

**Comment by plexus** [comment]
Sweet! I'll go ahead and merge this, the Travis config needs looking at, so you're not gonna get a green build as it is.

**Pull request merged**
