### PR TITLE
Attribute with options

### PR DESCRIPTION
**Pull request by hallgren**
Issue #113

### CODE REVIEW

**Comment by groyoh** [comment]
I restarted the failing build, should pass now :wink:

**Comment by bjoska** [comment]
Still seeing failing builds on 1.9.3. Perhaps needs cache clear?

**Comment by bjoska** [comment]
Seems the gem issue has been around for a while. Will need a look at the dependencies.

**Comment by groyoh** [comment]
Seems to be a known issue https://github.com/travis-ci/travis-ci/issues/5145.

**Comment by hallgren** [comment]
Have you tried turning it off and on again?

**Comment by plexus** [comment]
The problem is that `mime-types >= 3` requires Ruby 2. This is also causing issues on JRuby, seems it runs in 1.9 mode. I'll make sure master runs green again and then you can rebase. I'm also dropping rubocop, too many new cops to disable with each release.

**Comment by plexus** [comment]
Master is green again, please rebase and I'll merge. Code looks good.

**Comment by plexus** [comment]
thanks!

jake_thumbs_up

**Comment by hallgren** [comment]
St's me who should say thanks for this great tool.

**Comment by plexus** [comment]
Always a pleasure! What are you using it for?

**Comment by hallgren** [comment]
Building a hypermedia api :)

I really like the possibility that I can render the data as HTML or json (halo) with the same mapper. Making it easy to debug via the browser, and doing real stuff before the js app are supporting the feature.

For me a hypermedia API is all about links and forms and Yaks are doing that really good.

**Pull request merged**
