### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fnordfish**
- updating anima to 0.3.0 (#123)
- allow sinatra 2.0

### CODE REVIEW

**Comment by plexus** [comment]
Seems there's a problem installing a gem with C exts on Ruby 2.4.0. Is there anything else that needs updating? 

https://travis-ci.org/plexus/yaks/jobs/208618189

**Comment by fnordfish** [comment]
transit-ruby has a dependency on an old msgpack (0.5.12), which seems to be not working on ruby 2.4.0

**Comment by fnordfish** [comment]
Any thoughts on using something like appraisal for managing different testing environments? Eg. also testing yaks-sinatra agaist multiple versions of sinatra.

**Comment by plexus** [comment]
I have no experience with it, you're welcome to add it.

I reported the issue to ruby-transit. Will see what happens, Cognitect projects don't typically take pull requests.

https://github.com/cognitect/transit-ruby/issues/21

**Comment by plexus** [comment]
Ooh speedy response from Cognitect, cool!

**Pull request merged**
