### PR TITLE
Display top level links for JSON API

### PR DESCRIPTION
**Pull request by janko-m**
Currently, if you have

```rb
class CollectionMapper < Yaks::CollectionMapper
  link :next, '/link/to/next/page'
end
```

the "next" link won't be displayed anywhere. So I added it to be displayed according to the spec:

```json
{
  "links": {
    "next": "/link/to/next/page"
  },
  "data": [
    {"type": "..."},
    {"type": "..."}
  ]
}
```

### CODE REVIEW

**Comment by plexus** [comment]
Looks good. Mutation coverage did drop a bit for `Yaks::Format::JsonAPI`, from 100% to 99.55%. You can run mutant like this

``` ruby
PATTERN='Yaks::Format::JsonAPI*' bundle exec rake mutant
```

And it will show you for which bits of code test cases are missing. You can find an introduction to mutant [here](http://www.sitepoint.com/mutation-testing-mutant/)

**Comment by janko-m** [comment]
Oops, forgot about mutant. Fixed it :). It's impressive that you maintain 100% mutant coverage, the failing mutations were really relevant and caught some things I've missed. I should definitely try it in my projects!

**Comment by plexus** [comment]
We're not at 100% at the moment. We were some time back, then added a lot of features (especially regarding forms) which made it drop significantly. I've been making an effort lately to at least get the `yaks` gem code back to 100%. As you see it really does catch some interesting stuff.

I've also been aiming more for "explicit" mutation coverage, meaning that every method has its own set of tests. This helps mutant to do better test selection which speeds things up a lot. A total mutant run used to take ~2000 seconds, where now it's ~800. You can find mutant stats in the `git log`, I occasionally add an empty commit with current mutant stats in the message.

**Comment by janko-m** [comment]
I rebased after rubocop PR to solve the merge conflicts. I disabed one Rubocop offense deliberately, because putting a comma after the last element of a multiline array or hash is just objectively better ;) (easier editing, better diffs)

**Comment by plexus** [comment]
Thanks for this, great to see JSON-API support improving now that the spec is stabilizing.

**Comment by janko-m** [comment]
Wohooow, JSON-API changed again yesterday: https://github.com/json-api/json-api/pull/588/files
So much for backwards compatibility. I hope it will reach 1.0 soon.

**Comment by plexus** [comment]
Ouch... I feel sorry for people that betted on JSON-API. We almost went with it end of 2013. You wouldn't recognize it any more now.

**Pull request merged**
